// Generated by CoffeeScript 1.6.2
/*
// ==UserScript==
// @id             gamer_images_shower
// @name           Gamer images shower
// @version        1.0.0
// @namespace      http://blog.k2ds.net/
// @author         killtw
// @description    在未登入階段自動載入圖片
// @match          http://forum.gamer.com.tw/C.php?*
// @match          http://forum.gamer.com.tw/G2.php?*
// @include        http://forum.gamer.com.tw/C.php?*
// @include        http://forum.gamer.com.tw/G2.php?*
// ==/UserScript==
*/

var attach_img;

if (document.getElementsByClassName('TOP-my')[0].childNodes[0].href === 'https://user.gamer.com.tw/login.php') {
  attach_img = function() {
    var image, _i, _len, _ref;

    _ref = document.getElementsByName('attachImgName');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      image = _ref[_i];
      image.innerHTML = "<img src=" + image.id + "></img>";
    }
  };
  window.addEventListener('load', attach_img, false);
  window.addEventListener('AutoPagerAfterInsert', attach_img, false);
}
